trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: infra-rs-ntd-common-v1
  - group: infra-terraform-common-v1
  - group: infra-ntd-secrets-v1
  - name: environment
    ${{ if eq( variables['Build.SourceBranchName'], 'dev' ) }}:
      value: dev
    ${{ if eq( variables['Build.SourceBranchName'], 'staging' ) }}:
      value: staging
    ${{ if eq( variables['Build.SourceBranchName'], 'prod' ) }}:
      value: prod

stages:
  - template: /workflows/default/terragrunt_validate_and_plan.yml
  - template: /workflows/default/terragrunt_apply.yml

  - template: /workflows/default/kubernetes_tools_setup.yml
