trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: infra-ntd-common-v2
  - group: infra-ntd-secrets-v2
  - name: environment
    ${{ if eq( variables['Build.SourceBranchName'], 'dev' ) }}:
      value: dev
    ${{ if eq( variables['Build.SourceBranchName'], 'staging' ) }}:
      value: staging
    ${{ if eq( variables['Build.SourceBranchName'], 'prod' ) }}:
      value: prod

stages:
  - template: /workflows/default/terragrunt_destroy.yml
